from collections import Counter

from app.schemas.incident_context import IncidentContext, SummaryResponse


def _infer_attack_type(context: IncidentContext) -> tuple[str, str]:
    rule_ids = {a.rule_id for a in context.alerts}
    if "suspicious_login_v1" in rule_ids and "data_exfil_v1" in rule_ids:
        return "Account Compromise with Data Exfiltration", "Credential Access / Exfiltration"
    if "suspicious_login_v1" in rule_ids:
        return "Suspected Account Compromise", "Credential Access"
    if "brute_force_v1" in rule_ids:
        return "Brute Force Attack", "Credential Access"
    if "data_exfil_v1" in rule_ids:
        return "Data Exfiltration", "Exfiltration"
    if "port_scan_v1" in rule_ids:
        return "Network Reconnaissance", "Discovery"
    return "Suspicious Multi-Stage Activity", "Unknown"


def generate_fallback_summary(context: IncidentContext) -> SummaryResponse:
    event_types = Counter(e.event_type for e in context.events)
    alert_titles = [a.title for a in context.alerts]
    attack_type, category = _infer_attack_type(context)

    failed_logins = event_types.get("login_failed", 0)
    successful_logins = event_types.get("login_success", 0)
    downloads = event_types.get("file_download", 0)

    key_findings = []
    if failed_logins:
        key_findings.append(f"{failed_logins} failed login attempt(s) recorded for {context.username or 'target account'}.")
    if successful_logins:
        key_findings.append(
            f"{successful_logins} successful login(s) observed from IP {context.ip or 'unknown'} after failed attempts."
        )
    if downloads:
        key_findings.append(f"{downloads} file download event(s) suggest possible data gathering or exfiltration.")
    if alert_titles:
        key_findings.append(f"Detection rules triggered: {', '.join(alert_titles)}.")

    summary = (
        f"Incident '{context.title}' ({context.severity} severity) involves user "
        f"{context.username or 'unknown'} from IP {context.ip or 'unknown'}. "
        f"Evidence indicates {attack_type.lower()}. "
        f"{len(context.alerts)} alert(s) and {len(context.events)} related event(s) support this assessment."
    )

    markdown = f"""# SOC Investigation Summary

## Incident Overview
- **Title:** {context.title}
- **Severity:** {context.severity}
- **User:** {context.username or 'N/A'}
- **Source IP:** {context.ip or 'N/A'}

## Assessment
{summary}

## Key Findings
{chr(10).join(f'- {f}' for f in key_findings)}

## Threat Classification
- **Attack Type:** {attack_type}
- **Category:** {category}

## Recommended Actions
- Lock or reset credentials for affected account `{context.username or 'unknown'}`
- Block or monitor source IP `{context.ip or 'unknown'}`
- Review downloaded file audit logs and notify data owner
- Escalate to Tier 2 if exfiltration is confirmed

---
*Generated by ThreatLens AI (rule-based fallback — set OPENAI_API_KEY for LLM analysis)*
"""

    recommendations = [
        {
            "actionType": "lock_account",
            "description": f"Temporarily lock account {context.username or 'unknown'} pending verification",
            "priority": "high",
        },
        {
            "actionType": "block_ip",
            "description": f"Block or isolate IP {context.ip or 'unknown'} at the network edge",
            "priority": "high",
        },
        {
            "actionType": "force_password_reset",
            "description": "Force password reset and require MFA enrollment",
            "priority": "medium",
        },
    ]

    return SummaryResponse(
        summary=summary,
        markdown=markdown,
        key_findings=key_findings,
        threat_classification={
            "attackType": attack_type,
            "category": category,
            "confidence": 0.75,
        },
        recommendations=recommendations,
        confidence=0.75,
        source="fallback",
    )
