/** Parse SOC report markdown into structured sections for the report viewer. */

function extractTableRows(block) {
  const lines = block.split('\n').filter((l) => l.trim().startsWith('|'));
  if (lines.length < 2) return [];
  return lines
    .slice(2)
    .map((line) =>
      line
        .split('|')
        .map((c) => c.trim())
        .filter(Boolean)
    )
    .filter((row) => row.length >= 2);
}

function extractListItems(block) {
  return block
    .split('\n')
    .filter((l) => /^[-*]\s/.test(l.trim()))
    .map((l) => l.replace(/^[-*]\s+/, '').replace(/\*\*/g, '').trim());
}

export function parseSocReportMarkdown(markdown = '') {
  if (!markdown) return { sections: [], metadata: {} };

  const parts = markdown.split(/^## /m).filter(Boolean);
  const sections = {};
  const metadata = {};

  for (const part of parts) {
    const nl = part.indexOf('\n');
    const title = part.slice(0, nl).trim();
    const body = part.slice(nl + 1).trim();

    if (title === 'Report Metadata') {
      const idMatch = body.match(/\*\*Report ID:\*\*\s*(.+)/);
      const incMatch = body.match(/\*\*Incident ID:\*\*\s*(.+)/);
      const genMatch = body.match(/\*\*Generated:\*\*\s*(.+)/);
      const byMatch = body.match(/\*\*Generated By:\*\*\s*(.+)/);
      const verMatch = body.match(/\*\*Version:\*\*\s*(\d+)/);
      if (idMatch) metadata.reportId = idMatch[1].trim();
      if (incMatch) metadata.incidentId = incMatch[1].trim();
      if (genMatch) metadata.generatedAt = genMatch[1].trim();
      if (byMatch) metadata.generatedBy = byMatch[1].trim();
      if (verMatch) metadata.version = verMatch[1].trim();
      sections.metadata = body;
    } else if (title === 'Incident Overview') {
      sections.overviewTable = extractTableRows(body);
    } else if (title === 'Evidence (Recent Events)') {
      sections.evidenceTable = extractTableRows(body);
    } else {
      sections[title] = body;
    }
  }

  return { sections, metadata };
}

export function outputPreview(output) {
  if (!output) return null;
  if (typeof output === 'string') return output.slice(0, 160);
  const text = output.summary || output.executiveSummary || output.evidenceSummary || output.attackType;
  if (text) return String(text).slice(0, 160);
  return JSON.stringify(output).slice(0, 160);
}
