import Alert from '../../models/Alert.js';
import PlaybookAction from '../../models/PlaybookAction.js';
import SecurityEvent from '../../models/SecurityEvent.js';
import { loadIncidentBundle } from '../incident/incidentLoader.js';

export function buildSocReportMarkdown({
  incident,
  alerts,
  events,
  agentOutputs,
  playbookActions,
  generatedByName,
}) {
  const reportId = `SOC-${incident._id.toString().slice(-8).toUpperCase()}`;
  const generatedAt = new Date().toISOString();

  const alertLines = alerts.map(
    (a) => `- **${a.title}** (${a.severity}, ${a.status}) — ${a.evidence?.summary || 'No summary'}`
  );

  const eventLines = events.slice(0, 25).map(
    (e) => `| ${new Date(e.timestamp).toISOString()} | ${e.eventType} | ${e.username || '—'} | ${e.ip || '—'} | ${e.severity} |`
  );

  const agentSections = agentOutputs.map((a) => {
    const output = typeof a.output === 'string' ? a.output : JSON.stringify(a.output, null, 2);
    return `### ${a.agentName}\n${output}\n`;
  });

  const playbookLines = playbookActions.map(
    (p) => `- **${p.actionType}** [${p.status}] — ${p.description}`
  );

  const reviewer = agentOutputs.find((a) => a.agentName === 'reviewer');
  const classification = incident.threatClassification || {};
  const triage = agentOutputs.find((a) => a.agentName === 'triage');
  const investigation = agentOutputs.find((a) => a.agentName === 'investigation');

  return `# SOC Investigation Report

## Report Metadata
- **Report ID:** ${reportId}
- **Incident ID:** ${incident._id}
- **Generated:** ${generatedAt}
- **Generated By:** ${generatedByName || 'ThreatLens AI Analyst'}
- **Version:** ${incident.report?.version || 1}

## Executive Summary
${incident.aiSummary || 'No AI summary available.'}

## Incident Overview
| Field | Value |
|-------|-------|
| Title | ${incident.title} |
| Severity | ${incident.severity} |
| Status | ${incident.status} |
| Affected User | ${incident.username || 'Unknown'} |
| Source IP | ${incident.ip || 'Unknown'} |

## Threat Classification
- **Attack Type:** ${classification.attackType || 'Under investigation'}
- **Category:** ${classification.category || 'N/A'}
- **Confidence:** ${classification.confidence != null ? `${Math.round(classification.confidence * 100)}%` : 'N/A'}

## AI Triage Summary
${triage?.output?.summary || triage?.output?.priority || incident.aiSummary || 'Not available.'}

## Investigation Summary
${investigation?.output?.evidenceSummary || investigation?.output?.summary || 'See timeline and evidence below.'}

## Root Cause Analysis
${investigation?.output?.rationale || investigation?.output?.rootCause || 'Correlated alerts and events suggest coordinated suspicious activity on the affected account and source IP.'}

## Impact Assessment
${triage?.output?.impact || 'Potential account compromise and data access risk. Simulated SOC assessment — no real systems affected.'}

## Timeline
${(incident.timeline || []).map((t) => `- ${new Date(t.timestamp).toISOString()} — **${t.title}**: ${t.description || ''}`).join('\n') || 'No timeline entries.'}

## Alerts Triggered
${alertLines.length ? alertLines.join('\n') : 'No alerts linked.'}

## Evidence (Recent Events)
| Timestamp | Event Type | User | IP | Severity |
|-----------|------------|------|-----|----------|
${eventLines.join('\n') || '| — | — | — | — | — |'}

## Mitigation Recommendations
${(incident.recommendations || []).map((r) => `- **${r.actionType}** (${r.priority}): ${r.description}`).join('\n') || 'None.'}

## Playbook Actions
${playbookLines.length ? playbookLines.join('\n') : 'No playbook actions recorded.'}

## Agent Outputs
${agentSections.join('\n') || 'No agent outputs.'}

## Reviewer Notes
${reviewer?.output?.warnings?.length ? reviewer.output.warnings.map((w) => `- ${w}`).join('\n') : reviewer?.output?.notes || 'No reviewer warnings.'}

## Final Conclusion
${incident.aiSummary || incident.title} — Investigation completed via ThreatLens AI multi-agent workflow. All response actions require human approval before execution.
`;
}

export async function buildReportForIncident(incidentId, generatedByUser) {
  const bundle = await loadIncidentBundle(incidentId);
  if (!bundle) return null;

  const { incident, alerts, events } = bundle;
  const agentOutputs = await import('../../models/AgentOutput.js').then((m) =>
    m.default.find({ incidentId }).sort({ createdAt: 1 })
  );
  const playbookActions = await PlaybookAction.find({ incidentId }).sort({ createdAt: 1 });

  const markdown = buildSocReportMarkdown({
    incident,
    alerts,
    events,
    agentOutputs,
    playbookActions,
    generatedByName: generatedByUser?.name,
  });

  incident.report = {
    markdown,
    generatedAt: new Date(),
    version: (incident.report?.version || 0) + 1,
    generatedBy: generatedByUser?._id,
  };
  await incident.save();

  return { incident, markdown };
}
